// This file will be auto-generated by drizzle-kit introspect
// Run: bunx drizzle-kit introspect
// After adding your DATABASE_URL to .env.local

// Placeholder - will be replaced by introspection
export {};
